{{- range $job :=  $.Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-%s" (include "teko.fullname" $) $job.name (($.Values | toJson) | sha1sum | trunc 8) }}
  labels:
    app.kubernetes.io/instance: {{ printf "%s-%s" (include "teko.name" $) $job.name }}
    {{- include "teko.labels" $ | nindent 4 }}
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "teko.name" $ }}
        app.kubernetes.io/instance: {{ printf "%s-%s" (include "teko.name" $) $job.name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ printf "%s-%s" (include "teko.name" $) $job.name }}
        image: {{ printf "%s:%s" $.Values.image.repository $.Values.image.tag | quote }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- include "teko.cmd" $job | nindent 8}}
        {{- include "teko.env" (mergeOverwrite dict ($.Values.env | default dict) ($job.env | default dict)) | nindent 8 }}
        {{- include "teko.resources" ($job.resources | default ($.Values.resources | default dict)) | nindent 8 }}
      restartPolicy: Never
  backoffLimit: {{ .backoffLimit | default 6 }}
{{- end }}
